server:
  port: 5200
spring:
  application:
    name: aigou-product
  datasource:
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql:///aigou-product
