server:
  port: 5200
spring:
  application:
    name: aigou-product
   datasource:
    username: root
    password: 123456
    url: jdbc:mysql:///aigou-product?useUnicode=true&characterEncoding=utf8
    driver-class-name: com.mysql.jdbc.Driver