server:
  port: 1024
spring:
  application:
    name: zuul-client
zuul:
  routes: #后加上提供商的名字
   aigou-plat: 
    path: /user/**
    serviceId: aigou-plat
   aigou-product: 
    path: /product/**
    serviceId: aitou-product
   # myUser.serviceId: user-provider #这是调用满足条件的服务名，注意要小写
   # myUser.path: /user/** #这是所有路径前的通配
  ignored-services: "*" #用*来通配符，忽略从9527端口通过服务名来调用
  #prefix: /services #这是所有路径的前缀
  #访问地址如下：http://localhost:9527/services/user/provider/user/3
